### ISSUE TITLE
Error Encountered at Line 192 in tinyimagenet_eval_msp.py During Re-implementation

### ISSUE THREAD

**Issue by yjh576** [Harryqu123/LMC#2]
I encountered an error while re-implementing your code. I have ensured that the tiny-imagenet-200 dataset was downloaded following the instructions in your shell script. The error occurs specifically at line 192 in the file tinyimagenet_eval_msp.py from the repository https://github.com/Harryqu123/LMC/blob/67cc6bb02e8af5b3168ea2782dfb2ead2b6a1455/tinyimagenet_eval_msp.py#L192 

The detailed error report is as follows:

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/share/data/tiny-imagenet-200/0'

**Comment by Harryqu123** [comment]
Hi, thank you for your interest in our LMC.

It seems that you have inputted '/mnt/share/data/tiny-imagenet-200/' for args.image_path. Yet, this argument is to input the unzipped folder for the generated by DALL-E (as introduced in Eq. 1 in our paper). We provide the images generated in our experiments in tiny_img.zip. If you follow the instructions in README.md to unzip the provided images, the command to evaluate the code should be:

``python tinyimagenet_eval_msp.py --image_path tiny_img``

Could you please try again and see if it works?

**Comment by yjh576** [comment]
Yes, It works well. Thank you for your help!
